### PR TITLE
add Co-Borr Marital Status to BORROWER_PAIR_FIELDS

### PR DESCRIPTION
**Pull request by kurie**

### CODE REVIEW

**Comment by jeffpsherman** [comment]
@kurie - We finally got through the mess from the logging and metrics cutover.

If you merge with master and bump the version I'll merge this today

**Comment by kurie** [comment]
@jeffpsherman I rebased it on master, but I don't see any instructions in the readme about versioning. Can you bump the version for me?

**Comment by brianbegygr** [comment]
I got ya.

**Comment by kurie** [comment]
@brianbegygr just so's I know in the future, what do the 4 version parts mean? Is the leading 17 an encompass version number and the rest are the usual semver parts? (And is there a script to bump it)

**Pull request merged**
